//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "64197570596ec4be0494b852"
}

###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Test Testsson",
  "email": "Test@mail.com",
  "password": "test"
}

###

// LOGGA IN USER // VID FEL LÖSENORD SÅ SKALL SVARA MED 401
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "Test@mail.com",
  "password": "test"
}

###

//
// API ENDPOINTS PRODUCTS
//

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/641afb9d8942bb4ee5b36d51

###

// SKAPA PRODUKT // UTAN TOKEN SÅ SKALL ANROPET MISSLYCKAS = 401
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Produkt 3",
  "description": "Beskrivning av produkt 1",
  "price": 100,
  "lager": 10,
  "category": "6419b52ed2355db10ecf2435",
  "token": "2e2a7fa8-6511-4037-af7a-31c6e9139e3d"
}

###

// HÄMTA ALLA PRODUKTER FÖR EN SPECIFIK KATEGORI
GET http://localhost:3000/api/products/category/6419b52ed2355db10ecf2435

###


//
// API ENDPOINTS KATEGORI
// 

// SKAPA KATEGORI, KEY MÅSTE ANGES // UTAN KEY SVARA 401
# @name createCategory
POST http://localhost:3000/api/categories/add
Content-Type: application/json

{
  "name": "TEST",
  "token": "20844d14-8191-4a1f-8fe5-c5f2860641cd"
}

###

# @name getCategories
GET http://localhost:3000/api/categories

###


//
// API ENDPOINTS ORDERS
//

// HÄMTA ALLA ORDERS, KEY MÅSTE ANGES FÖR ATT FÅ TILLGÅNG TILL ORDERS
GET http://localhost:3000/api/orders/all/b09b6eb8-c931-4b29-9ce0-49ea9ad1d74a

###

// HÄMTA ALLA ORDER, FEL KEY // SKALL MISSLYCKAS
GET http://localhost:3000/api/orders/all/feltoken

###

// SKAPA ORDER FÖR EN SPECIFIK USER
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
	"user": "641b199fb70d140f7700d1b4",
	"products": [
    {
      "productId": "111",
      "quantity": 1
    },
    {
      "productId": "222",
      "quantity": 2
    }
  ]
}

###

// HÄMTA ORDERS FÖR EN USER // SKALL MISSLYCKAS = INGEN KEY  // SVARA MED 401
POST http://localhost:3000/api/orders/user
Content-Type: application/json

{
    "user": "641b199fb70d140f7700d1b4"
}
###

// HÄMTA ORDERS FÖR EN USER // SKALL LYCKAS = KEY
POST http://localhost:3000/api/orders/user
Content-Type: application/json

{
    "user": "641b199fb70d140f7700d1b4",
    "token": "1234key1234"
}
###